export const recommendInit = {
  RECOMMEND_INIT_REQUEST: 'RECOMMEND_INIT_REQUEST',
  RECOMMEND_INIT_SUCCESS: 'RECOMMEND_INIT_SUCCESS',
  RECOMMEND_INIT_FAILURE: 'RECOMMEND_INIT_FAILURE'
};

export const recommendBreak = {
  RECOMMEND_BREAK_REQUEST: 'RECOMMEND_BREAK_REQUEST',
  RECOMMEND_BREAK_SUCCESS: 'RECOMMEND_BREAK_SUCCESS',
  RECOMMEND_BREAK_FAILURE: 'RECOMMEND_BREAK_FAILURE'
};

export const recommendMore = {
  RECOMMEND_MORE_REQUEST: 'RECOMMEND_MORE_REQUEST',
  RECOMMEND_MORE_SUCCESS: 'RECOMMEND_MORE_SUCCESS',
  RECOMMEND_MORE_FAILURE: 'RECOMMEND_MORE_FAILURE'
};
